package com.cgi.backend.service;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

import org.springframework.stereotype.Service;

import com.cgi.backend.dto.AvailableTimesDTO;
import com.cgi.backend.entity.Table;
import com.cgi.backend.repository.ReservationRepository;
import com.cgi.backend.repository.TableRepository;

// This class was generated by AI
@Service
public class TimeAvailabilityService {

    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("HH:mm");
    private static final int OPENING_HOUR = 9;
    private static final int WEEKDAY_CLOSING_HOUR = 22;
    private static final int WEEKEND_CLOSING_HOUR = 23;
    private static final int MORNING_LUNCH_DURATION_MINUTES = 90;
    private static final int EVENING_DURATION_MINUTES = 150;
    private static final int STEP_MINUTES = 15;

    private final TableRepository tableRepository;
    private final ReservationRepository reservationRepository;

    public TimeAvailabilityService(TableRepository tableRepository, ReservationRepository reservationRepository) {
        this.tableRepository = tableRepository;
        this.reservationRepository = reservationRepository;
    }

    public AvailableTimesDTO getAvailableTimes(LocalDate date, int guests, String location) {
        int normalizedGuests = Math.max(1, guests);
        String normalizedLocation = location == null ? "" : location.trim();
        String normalizedLocationLower = normalizedLocation.toLowerCase(Locale.ROOT);

        List<Table> eligibleTables = tableRepository.findAll().stream()
            .filter(table -> table.getCapacity() >= normalizedGuests)
            .filter(table -> matchesLocation(table, normalizedLocationLower))
            .toList();

        List<String> availableTimes = buildStartTimes(date).stream()
            .filter(startTime -> isAnyTableAvailable(eligibleTables, startTime))
            .map(startTime -> startTime.format(TIME_FORMAT))
            .toList();

        return new AvailableTimesDTO(
            date.toString(),
            normalizedGuests,
            normalizedLocation,
            MORNING_LUNCH_DURATION_MINUTES,
            availableTimes
        );
    }

    private List<LocalDateTime> buildStartTimes(LocalDate date) {
        LocalDateTime openTime = date.atTime(OPENING_HOUR, 0);
        int closingHour = isWeekend(date) ? WEEKEND_CLOSING_HOUR : WEEKDAY_CLOSING_HOUR;
        LocalDateTime closingTime = date.atTime(closingHour, 0);

        java.util.ArrayList<LocalDateTime> starts = new java.util.ArrayList<>();
        for (LocalDateTime current = openTime; current.isBefore(closingTime); current = current.plusMinutes(STEP_MINUTES)) {
            int durationMinutes = reservationDurationMinutes(current);
            if (!current.plusMinutes(durationMinutes).isAfter(closingTime)) {
                starts.add(current);
            }
        }

        return starts;
    }

    private boolean isAnyTableAvailable(List<Table> eligibleTables, LocalDateTime startTime) {
        if (eligibleTables.isEmpty()) {
            return false;
        }

        LocalDateTime endTime = startTime.plusMinutes(reservationDurationMinutes(startTime));
        List<Long> occupiedTableIds = reservationRepository.findOccupiedTableIds(startTime, endTime);

        return eligibleTables.stream().anyMatch(table -> !occupiedTableIds.contains(table.getId()));
    }

    private static boolean matchesLocation(Table table, String normalizedLocationLower) {
        if (normalizedLocationLower.isBlank()) {
            return true;
        }

        if (table.getFeatures() == null || table.getFeatures().isEmpty()) {
            return false;
        }

        return table.getFeatures().stream()
            .filter(feature -> feature != null)
            .map(feature -> feature.toLowerCase(Locale.ROOT))
            .anyMatch(feature -> feature.contains(normalizedLocationLower));
    }

    private static boolean isWeekend(LocalDate date) {
        DayOfWeek day = date.getDayOfWeek();
        return day == DayOfWeek.SATURDAY || day == DayOfWeek.SUNDAY;
    }

    private static int reservationDurationMinutes(LocalDateTime startTime) {
        if (startTime.getHour() < 17) {
            return MORNING_LUNCH_DURATION_MINUTES;
        }

        return EVENING_DURATION_MINUTES;
    }
}