import { useState, useEffect } from 'react'
import './App.css'

const LOCATION_OPTIONS = [
  { label: 'All locations', value: '' },
  { label: 'Near Window', value: 'Near Window' },
  { label: 'Private Booth', value: 'Private Booth' },
  { label: 'Terrace', value: 'Terrace' },
  { label: 'Middle of the Room', value: 'Middle of the Room' },
]

function getDefaultDate() {
  const now = new Date()
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
}

function getTimeSections(times) {
  const sections = [
    { key: 'morning', title: 'Morning Service', times: [] },
    { key: 'midday', title: 'Midday Service', times: [] },
    { key: 'evening', title: 'Evening Service', times: [] },
  ]

  times.forEach((timeValue) => {
    const hour = Number(timeValue.split(':')[0])

    if (Number.isNaN(hour)) {
      return
    }

    if (hour < 12) {
      sections[0].times.push(timeValue)
      return
    }

    if (hour < 17) {
      sections[1].times.push(timeValue)
      return
    }

    sections[2].times.push(timeValue)
  })

  return sections.filter(section => section.times.length > 0)
}

function App() {
  const [availableTimes, setAvailableTimes] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [date, setDate] = useState(getDefaultDate)
  const [guests, setGuests] = useState(2)
  const [location, setLocation] = useState('')
  const timeSections = getTimeSections(availableTimes)

  useEffect(() => {
    const loadAvailableTimes = async () => {
      setLoading(true)
      setError('')

      try {
        const query = new URLSearchParams({
          date,
          guests: String(Math.max(1, guests)),
        })

        if (location) {
          query.set('location', location)
        }

        const res = await fetch(`/api/tables/available-times?${query.toString()}`)

        if (!res.ok) {
          const status = `${res.status}${res.statusText ? ` ${res.statusText}` : ''}`
          const contentType = res.headers.get('content-type') || ''
          let detail = ''

          if (contentType.includes('application/json')) {
            const body = await res.json()
            detail = body?.message || body?.error || ''
          } else {
            detail = await res.text()
          }

          const trimmedDetail = typeof detail === 'string' ? detail.trim() : ''
          throw new Error(
            `${status}${trimmedDetail ? `: ${trimmedDetail}` : ''}`
          )
        }

        const data = await res.json()
        setAvailableTimes(Array.isArray(data?.availableTimes) ? data.availableTimes : [])
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : 'Unknown error occurred.'
        )
        setAvailableTimes([])
      } finally {
        setLoading(false)
      }
    }

    loadAvailableTimes()
  }, [date, guests, location])

  // Generated by AI - start
  return (
    <section className="availability-page">
      <header className="availability-header">
        <h1>CGI Restaurant</h1>
        <p>Choose date, guests and location to see only available start times.</p>
      </header>

      <section className="filter-form" aria-label="Availability filters">
        <label>
          Date
          <input
            type="date"
            value={date}
            onChange={(event) => setDate(event.target.value)}
          />
        </label>

        <label>
          Number of people
          <input
            type="number"
            min="1"
            max="20"
            value={guests}
            onChange={(event) => setGuests(Number(event.target.value) || 1)}
          />
        </label>

        <label>
          Location
          <select
            value={location}
            onChange={(event) => setLocation(event.target.value)}
          >
            {LOCATION_OPTIONS.map(option => (
              <option key={option.label} value={option.value}>{option.label}</option>
            ))}
          </select>
        </label>
      </section>

      <section className="availability-results" aria-live="polite">
          {loading ? (
            <p>Loading available times...</p>
          ) : error ? (
            <p className="error-message" role="alert">
              <span className="error-icon" aria-hidden="true">X</span>
              <span>{error}</span>
            </p>
          ) : availableTimes.length === 0 ? (
            <p>No available start times for the selected criteria.</p>
          ) : (
            <div className="time-sections">
              {timeSections.map(section => (
                <section className="time-section" key={section.key}>
                  <h2>{section.title}</h2>
                  <ul className="time-list">
                    {section.times.map(time => (
                      <li key={`${section.key}-${time}`} className="time-chip">{time}</li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          )}

        <p className="reservation-info">
          <span className="reservation-info-icon" aria-hidden="true">i</span>
          <span>Morning and Lunch reservations are 1,5 hours. Evening reservations are 2,5 hours.</span>
        </p>
      </section>
    </section>
    // Generated by AI - end
  )
}

export default App
