import { useState, useEffect, useRef } from 'react'
import './App.css'
import { COUNTRY_CODE_OPTIONS, DEFAULT_COUNTRY_CODE } from './countryCodeOptions'

const LOCATION_OPTIONS = [
  { label: 'All locations', value: '' },
  { label: 'Near Window', value: 'Near Window' },
  { label: 'Private Booth', value: 'Private Booth' },
  { label: 'Terrace', value: 'Terrace' },
  { label: 'Regular', value: 'Regular' },
]

// Generated by AI - start
const NAME_REGEX = /^[\p{L}][\p{L}' -]{1,79}$/u
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/
const PHONE_REGEX = /^[0-9\s()-]{4,20}$/
const OPTIONAL_INFO_REGEX = /^[\p{L}\p{N}\s.,!?\-_'"():;@#&+/]{0,200}$/u
// Generated by AI - end

function getDefaultDate() {
  const now = new Date()
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
}

function formatDateForDisplay(dateValue) {
  const [year, month, day] = String(dateValue).split('-')

  if (!year || !month || !day) {
    return dateValue
  }

  return `${day}.${month}.${year}`
}

function getTimeSections(times) {
  const sections = [
    { key: 'morning', title: 'Morning Service', times: [] },
    { key: 'midday', title: 'Midday Service', times: [] },
    { key: 'evening', title: 'Evening Service', times: [] },
  ]

  times.forEach((timeValue) => {
    const hour = Number(timeValue.split(':')[0])

    if (Number.isNaN(hour)) {
      return
    }

    if (hour < 12) {
      sections[0].times.push(timeValue)
      return
    }

    if (hour < 17) {
      sections[1].times.push(timeValue)
      return
    }

    sections[2].times.push(timeValue)
  })

  return sections.filter(section => section.times.length > 0)
}

function getTablePosition(index) {
  const columns = 5
  const row = Math.floor(index / columns)
  const column = index % columns

  const xStart = 14
  const xStep = 18
  const yStart = 20
  const yStep = 30

  return {
    x: xStart + (column * xStep),
    y: yStart + (row * yStep),
  }
}

function getTableLocationLabel(features) {
  if (!Array.isArray(features) || features.length === 0) {
    return 'No location set'
  }

  const knownLocations = LOCATION_OPTIONS
    .filter(option => option.value)
    .map(option => option.label)

  const exactMatch = features.find(feature => knownLocations.includes(feature))

  if (exactMatch) {
    return exactMatch
  }

  const firstFeature = features.find(feature => typeof feature === 'string' && feature.trim())
  return firstFeature || 'No location set'
}

// Generated by AI - start
function App() {
  const today = getDefaultDate()
  const [availableTimes, setAvailableTimes] = useState([])
  const [availableTables, setAvailableTables] = useState([])
  const [loading, setLoading] = useState(true)
  const [tableLoading, setTableLoading] = useState(false)
  const [error, setError] = useState('')
  const [tableError, setTableError] = useState('')
  const [date, setDate] = useState(getDefaultDate)
  const [guests, setGuests] = useState(2)
  const [location, setLocation] = useState('')
  const [selectedTime, setSelectedTime] = useState('')
  const [selectedTableId, setSelectedTableId] = useState('')
  const [customerName, setCustomerName] = useState('')
  const [customerEmail, setCustomerEmail] = useState('')
  const defaultCountryOption = COUNTRY_CODE_OPTIONS.find(option => option.value === DEFAULT_COUNTRY_CODE)
  const [countryCode, setCountryCode] = useState(DEFAULT_COUNTRY_CODE)
  const [countrySearch, setCountrySearch] = useState(defaultCountryOption ? defaultCountryOption.label : '')
  const [contactNumber, setContactNumber] = useState('')
  const [optionalInfo, setOptionalInfo] = useState('')
  const [showFloorPlan, setShowFloorPlan] = useState(false)
  const [showConfirmation, setShowConfirmation] = useState(false)
  const [confirmationStatus, setConfirmationStatus] = useState('idle')
  const confirmationTimeoutRef = useRef(null)
  const timeSections = getTimeSections(availableTimes)
  const selectedTable = availableTables.find((table, index) => {
    const tableKey = String(table.id ?? table.tableNumber ?? index)
    return tableKey === selectedTableId
  })
  const phaseInstruction = showConfirmation
    ? 'Review your reservation details before confirming.'
    : showFloorPlan
      ? 'Select one available table on the floor plan to continue.'
      : 'Choose your date, amount of people, and preferred location, then pick a start time.'
  const trimmedCustomerName = customerName.trim()
  const trimmedCustomerEmail = customerEmail.trim()
  const trimmedCountrySearch = countrySearch.trim()
  const trimmedCountryCode = countryCode.trim()
  const trimmedContactNumber = contactNumber.trim()
  const trimmedOptionalInfo = optionalInfo.trim()
  const countryCodeDigits = trimmedCountryCode.replace(/\D/g, '')
  const contactNumberDigits = trimmedContactNumber.replace(/\D/g, '')
  const isNameValid = NAME_REGEX.test(trimmedCustomerName)
  const isEmailValid = EMAIL_REGEX.test(trimmedCustomerEmail)
  const isCountryCodeValid = COUNTRY_CODE_OPTIONS.some(option => option.value === trimmedCountryCode)
  const isContactNumberValid = PHONE_REGEX.test(trimmedContactNumber)
    && contactNumberDigits.length >= 4
    && contactNumberDigits.length <= 12
  const totalPhoneDigits = countryCodeDigits.length + contactNumberDigits.length
  const isPhoneLengthValid = totalPhoneDigits >= 7 && totalPhoneDigits <= 15
  const isOptionalInfoValid = trimmedOptionalInfo.length === 0 || OPTIONAL_INFO_REGEX.test(trimmedOptionalInfo)
  const isConfirmDisabled = !isNameValid
    || !isEmailValid
    || !isCountryCodeValid
    || !isContactNumberValid
    || !isPhoneLengthValid
    || !isOptionalInfoValid
    || !selectedTable
    || !selectedTime
  const contactDisplay = `${trimmedCountryCode} ${trimmedContactNumber}`.trim()

  const resetReservationView = () => {
    if (confirmationTimeoutRef.current) {
      clearTimeout(confirmationTimeoutRef.current)
      confirmationTimeoutRef.current = null
    }

    setSelectedTime('')
    setSelectedTableId('')
    setShowFloorPlan(false)
    setShowConfirmation(false)
    setConfirmationStatus('idle')
    setCustomerName('')
    setCustomerEmail('')
    setCountryCode(DEFAULT_COUNTRY_CODE)
    setCountrySearch(defaultCountryOption ? defaultCountryOption.label : '')
    setContactNumber('')
    setOptionalInfo('')
    setTableError('')
    setAvailableTables([])
  }

  const handleCountrySearchChange = (event) => {
    const nextValue = event.target.value
    setCountrySearch(nextValue)

    const matchedOption = COUNTRY_CODE_OPTIONS.find(option => (
      option.label === nextValue || option.value === nextValue
    ))

    setCountryCode(matchedOption ? matchedOption.value : '')
  }

  const handleReserveClick = async () => {
    if (!selectedTime) {
      return
    }

    setTableLoading(true)
    setTableError('')

    try {
      const query = new URLSearchParams({
        date,
        time: selectedTime,
        guests: String(Math.max(1, guests)),
      })

      if (location) {
        query.set('location', location)
      }

      const res = await fetch(`/api/tables/availability?${query.toString()}`)

      if (!res.ok) {
        const status = `${res.status}${res.statusText ? ` ${res.statusText}` : ''}`
        const detail = (await res.text()).trim()
        throw new Error(`${status}${detail ? `: ${detail}` : ''}`)
      }

      const data = await res.json()
      const tables = Array.isArray(data?.tables) ? data.tables : []
      const orderedTables = [...tables].sort((a, b) => (a.tableNumber ?? 0) - (b.tableNumber ?? 0))
      setAvailableTables(orderedTables)
      setSelectedTableId('')
      setShowFloorPlan(true)
      setShowConfirmation(false)
    } catch (err) {
      setTableError(err instanceof Error ? err.message : 'Failed to load table availability.')
      setSelectedTableId('')
      setShowFloorPlan(false)
      setShowConfirmation(false)
      setAvailableTables([])
    } finally {
      setTableLoading(false)
    }
  }

  const handleContinueFromFloorPlan = () => {
    if (!selectedTableId) {
      setTableError('Please select a table before continuing.')
      return
    }

    setTableError('')
    setConfirmationStatus('idle')
    setShowConfirmation(true)
  }

  const handleConfirmReservation = () => {
    if (isConfirmDisabled || confirmationStatus === 'loading') {
      return
    }

    if (confirmationTimeoutRef.current) {
      clearTimeout(confirmationTimeoutRef.current)
    }

    setConfirmationStatus('loading')
    confirmationTimeoutRef.current = setTimeout(() => {
      setConfirmationStatus('success')
      confirmationTimeoutRef.current = null
    }, 1500)
  }

  useEffect(() => {
    return () => {
      if (confirmationTimeoutRef.current) {
        clearTimeout(confirmationTimeoutRef.current)
      }
    }
  }, [])
  // Generated by AI - end
  
  useEffect(() => {
    const loadAvailableTimes = async () => {
      setLoading(true)
      setError('')

      try {
        const query = new URLSearchParams({
          date,
          guests: String(Math.max(1, guests)),
        })

        if (location) {
          query.set('location', location)
        }

        const res = await fetch(`/api/tables/available-times?${query.toString()}`)

        if (!res.ok) {
          const status = `${res.status}${res.statusText ? ` ${res.statusText}` : ''}`
          const contentType = res.headers.get('content-type') || ''
          let detail = ''

          if (contentType.includes('application/json')) {
            const body = await res.json()
            detail = body?.message || body?.error || ''
          } else {
            detail = await res.text()
          }

          const trimmedDetail = typeof detail === 'string' ? detail.trim() : ''
          throw new Error(
            `${status}${trimmedDetail ? `: ${trimmedDetail}` : ''}`
          )
        }

        const data = await res.json()
        const nextAvailableTimes = Array.isArray(data?.availableTimes) ? data.availableTimes : []
        setAvailableTimes(nextAvailableTimes)
        setSelectedTime((currentSelectedTime) => (
          nextAvailableTimes.includes(currentSelectedTime) ? currentSelectedTime : ''
        ))
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : 'Unknown error occurred.'
        )
        setAvailableTimes([])
        setSelectedTime('')
      } finally {
        setLoading(false)
      }
    }

    loadAvailableTimes()
  }, [date, guests, location])

  // Generated by AI - start
  return (
    <section className="availability-page">
      <header className="availability-header">
        <h1>CGI Restaurant</h1>
      </header>

      {!showConfirmation && <p className="phase-instruction">{phaseInstruction}</p>}

      {!showFloorPlan && !showConfirmation && (
      <section className="filter-form" aria-label="Availability filters">
        <label>
          Date
          <input
            type="date"
            value={date}
            min={today}
            onChange={(event) => {
              const selectedDate = event.target.value
              setDate(selectedDate < today ? today : selectedDate)
              resetReservationView()
            }}
          />
        </label>

        <label>
          Number of people
          <input
            type="number"
            min="1"
            max="20"
            value={guests}
            onChange={(event) => {
              setGuests(Number(event.target.value) || 1)
              resetReservationView()
            }}
          />
        </label>

        <label>
          Location
          <select
            value={location}
            onChange={(event) => {
              setLocation(event.target.value)
              resetReservationView()
            }}
          >
            {LOCATION_OPTIONS.map(option => (
              <option key={option.label} value={option.value}>{option.label}</option>
            ))}
          </select>
        </label>

      </section>
      )}

      <section className="availability-results" aria-live="polite">
          {showConfirmation ? (
            confirmationStatus === 'success' ? (
              <div className="confirmation-complete" role="status" aria-live="polite">
                <p className="confirmation-status success">
                  <span className="confirmation-checkmark" aria-hidden="true">✓</span>
                  <span>Thank you. Your reservation is confirmed.</span>
                </p>
                <dl className="confirmation-success-list">
                  <div>
                    <dt>Date</dt>
                    <dd>{formatDateForDisplay(date)}</dd>
                  </div>
                  <div>
                    <dt>Time</dt>
                    <dd>{selectedTime}</dd>
                  </div>
                  <div>
                    <dt>Guests</dt>
                    <dd>{Math.max(1, guests)}</dd>
                  </div>
                  <div>
                    <dt>Table</dt>
                    <dd>{selectedTable ? `Table ${selectedTable.tableNumber}` : '-'}</dd>
                  </div>
                  <div>
                    <dt>Table location</dt>
                    <dd>{selectedTable ? getTableLocationLabel(selectedTable.features) : '-'}</dd>
                  </div>
                  <div>
                    <dt>Name</dt>
                    <dd>{trimmedCustomerName}</dd>
                  </div>
                  <div>
                    <dt>Email</dt>
                    <dd>{trimmedCustomerEmail}</dd>
                  </div>
                  <div>
                    <dt>Phone number</dt>
                    <dd>{contactDisplay}</dd>
                  </div>
                  <div>
                    <dt>Additional info</dt>
                    <dd>{trimmedOptionalInfo || 'None'}</dd>
                  </div>
                </dl>
                <div className="timeslot-cta-wrap confirmation-actions">
                  <button
                    type="button"
                    className="timeslot-cta"
                    onClick={resetReservationView}
                  >
                    Back to reservation page
                  </button>
                </div>
              </div>
            ) : (
              <div className="confirmation-section">
                <h2>Reservation Confirmation</h2>
                <p className="confirmation-subtitle">Please review your reservation details.</p>

                <dl className="confirmation-list">
                  <div>
                    <dt>Date</dt>
                    <dd>{formatDateForDisplay(date)}</dd>
                  </div>
                  <div>
                    <dt>Time</dt>
                    <dd>{selectedTime}</dd>
                  </div>
                  <div>
                    <dt>Guests</dt>
                    <dd>{Math.max(1, guests)}</dd>
                  </div>
                  <div>
                    <dt>Table</dt>
                    <dd>
                      {selectedTable ? `Table ${selectedTable.tableNumber}` : 'No table selected'}
                    </dd>
                  </div>
                  <div>
                    <dt>Capacity</dt>
                    <dd>{selectedTable?.capacity ? `${selectedTable.capacity} seats` : '-'}</dd>
                  </div>
                  <div>
                    <dt>Table location</dt>
                    <dd>{selectedTable ? getTableLocationLabel(selectedTable.features) : '-'}</dd>
                  </div>
                </dl>

                <h3 className="confirmation-contact-title">Contact info</h3>

                <div className="confirmation-contact-fields">
                  <label>
                    Name
                    <input
                      type="text"
                      className="name-input"
                      value={customerName}
                      onChange={(event) => setCustomerName(event.target.value)}
                      placeholder="Enter your full name"
                      autoComplete="name"
                      aria-invalid={customerName.length > 0 && !isNameValid}
                    />
                  </label>

                  <label>
                    Email
                    <input
                      type="email"
                      className="email-input"
                      value={customerEmail}
                      onChange={(event) => setCustomerEmail(event.target.value)}
                      placeholder="name@example.com"
                      autoComplete="email"
                      aria-invalid={customerEmail.length > 0 && !isEmailValid}
                    />
                  </label>

                  <div className="confirmation-phone-row">
                    <label>
                      Country code
                      <input
                        type="text"
                        className="country-code-input"
                        value={countrySearch}
                        onChange={handleCountrySearchChange}
                        list="country-code-options"
                        placeholder="Select a country"
                        autoComplete="off"
                        aria-invalid={trimmedCountrySearch.length > 0 && !isCountryCodeValid}
                      />
                      <datalist id="country-code-options">
                        {COUNTRY_CODE_OPTIONS.map(option => (
                          <option key={option.label} value={option.label} />
                        ))}
                      </datalist>
                    </label>

                    <label>
                      Contact number
                      <input
                        type="tel"
                        className="contact-number-input"
                        value={contactNumber}
                        onChange={(event) => setContactNumber(event.target.value)}
                        placeholder="401234567"
                        autoComplete="tel"
                        inputMode="tel"
                        aria-invalid={contactNumber.length > 0 && (!isContactNumberValid || !isPhoneLengthValid)}
                      />
                    </label>

                    <label>
                      Additional info (optional)
                      <input
                        type="text"
                        className="optional-info-input"
                        value={optionalInfo}
                        onChange={(event) => setOptionalInfo(event.target.value)}
                        placeholder="Any special request"
                        aria-invalid={optionalInfo.length > 0 && !isOptionalInfoValid}
                      />
                    </label>
                  </div>
                </div>

                <p className="reservation-info">
                  <span className="reservation-info-icon" aria-hidden="true">i</span>
                  <span>Morning and Lunch reservations are 1,5 hours. Evening reservations are 2,5 hours.</span>
                </p>

                <div className="timeslot-cta-wrap confirmation-actions">
                  {confirmationStatus === 'idle' ? (
                    <>
                      <button
                        type="button"
                        className="timeslot-cta secondary-cta"
                        onClick={() => {
                          setConfirmationStatus('idle')
                          setShowConfirmation(false)
                        }}
                      >
                        Back to floor plan
                      </button>
                      <button
                        type="button"
                        className="timeslot-cta"
                        onClick={handleConfirmReservation}
                        disabled={isConfirmDisabled}
                      >
                        Confirm reservation
                      </button>
                    </>
                  ) : (
                    <p className="confirmation-status" role="status" aria-live="polite">
                      <span className="confirmation-spinner" aria-hidden="true" />
                      <span>Loading reservation status...</span>
                    </p>
                  )}
                </div>
              </div>
            )
          ) : showFloorPlan ? (
            <div className="floor-plan-section">
              <div className="floor-plan-heading">
                <div>
                  <h2>{selectedTime ? `Reserve ${selectedTime}` : 'Floor Plan'}</h2>
                  <p>
                    {formatDateForDisplay(date)} at {selectedTime} for {Math.max(1, guests)} guests
                    {location ? ` in ${location}` : ''}
                  </p>
                </div>
                <button
                  type="button"
                  className="timeslot-cta floor-plan-back"
                  onClick={() => {
                    setShowFloorPlan(false)
                    setShowConfirmation(false)
                  }}
                >
                  Back
                </button>
              </div>

              {tableError ? (
                <p className="error-message" role="alert">
                  <span className="error-icon" aria-hidden="true">X</span>
                  <span>{tableError}</span>
                </p>
              ) : availableTables.length === 0 ? (
                <p>No tables were found for this reservation.</p>
              ) : (
                <>
                  <div className="floor-plan-legend" aria-label="Table availability legend">
                    <span className="legend-item"><span className="legend-dot available" aria-hidden="true" />Available</span>
                    <span className="legend-item"><span className="legend-dot unavailable" aria-hidden="true" />Unavailable</span>
                  </div>

                  <div className="floor-plan-canvas" role="img" aria-label="Restaurant floor plan with table availability">
                    {availableTables.map((table, index) => {
                      const position = getTablePosition(index)
                      const tableKey = String(table.id ?? table.tableNumber ?? index)

                      return (
                        <div
                          key={tableKey}
                          className={`floor-table ${table.recommended ? 'available' : 'unavailable'}${selectedTableId === tableKey ? ' selected' : ''}`}
                          style={{ left: `${position.x}%`, top: `${position.y}%` }}
                          onClick={() => {
                            if (!table.recommended) {
                              return
                            }

                            setSelectedTableId(tableKey)
                            setTableError('')
                          }}
                        >
                          <strong>Table {table.tableNumber}</strong>
                          <span>{table.capacity} seats</span>
                          <span className="table-location">{getTableLocationLabel(table.features)}</span>
                        </div>
                      )
                    })}
                  </div>
                </>
              )}
            </div>
          ) : loading ? (
            <p>Loading available times...</p>
          ) : error ? (
            <p className="error-message" role="alert">
              <span className="error-icon" aria-hidden="true">X</span>
              <span>{error}</span>
            </p>
          ) : availableTimes.length === 0 ? (
            <p>No available start times for the selected criteria.</p>
          ) : (
            <div className="time-sections">
              {timeSections.map(section => (
                <section className="time-section" key={section.key}>
                  <h2>{section.title}</h2>
                  <ul className="time-list">
                    {section.times.map(time => (
                      <li key={`${section.key}-${time}`}>
                        <button
                          type="button"
                          className={`time-chip${selectedTime === time ? ' selected' : ''}`}
                          onClick={() => {
                            setSelectedTime(time)
                            setTableError('')
                          }}
                        >
                          {time}
                        </button>
                      </li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          )}

        {!loading && !error && availableTimes.length > 0 && !showConfirmation && (
          <div className="timeslot-cta-wrap">
            <button
              type="button"
              className="timeslot-cta"
              onClick={showFloorPlan ? handleContinueFromFloorPlan : handleReserveClick}
              disabled={showFloorPlan ? !selectedTableId : (!selectedTime || tableLoading)}
            >
              {showFloorPlan ? 'Next' : (tableLoading ? 'Loading floor plan...' : 'Next')}
            </button>
          </div>
        )}

        {!showFloorPlan && tableError && (
          <p className="error-message" role="alert">
            <span className="error-icon" aria-hidden="true">X</span>
            <span>{tableError}</span>
          </p>
        )}

        {!showConfirmation && (
        <p className="reservation-info">
          <span className="reservation-info-icon" aria-hidden="true">i</span>
          <span>Morning and Lunch reservations are 1,5 hours. Evening reservations are 2,5 hours.</span>
        </p>
        )}
      </section>
    </section>
    // Generated by AI - end
  )
}

export default App
