import { useState, useEffect } from 'react'
import './App.css'

const LOCATION_OPTIONS = [
  { label: 'All locations', value: '' },
  { label: 'Near Window', value: 'Near Window' },
  { label: 'Private Booth', value: 'Private Booth' },
  { label: 'Terrace', value: 'Terrace' },
  { label: 'Regular', value: 'Regular' },
]

function getDefaultDate() {
  const now = new Date()
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
}

function formatDateForDisplay(dateValue) {
  const [year, month, day] = String(dateValue).split('-')

  if (!year || !month || !day) {
    return dateValue
  }

  return `${day}-${month}-${year}`
}

function getTimeSections(times) {
  const sections = [
    { key: 'morning', title: 'Morning Service', times: [] },
    { key: 'midday', title: 'Midday Service', times: [] },
    { key: 'evening', title: 'Evening Service', times: [] },
  ]

  times.forEach((timeValue) => {
    const hour = Number(timeValue.split(':')[0])

    if (Number.isNaN(hour)) {
      return
    }

    if (hour < 12) {
      sections[0].times.push(timeValue)
      return
    }

    if (hour < 17) {
      sections[1].times.push(timeValue)
      return
    }

    sections[2].times.push(timeValue)
  })

  return sections.filter(section => section.times.length > 0)
}

function getTablePosition(index) {
  const columns = 5
  const row = Math.floor(index / columns)
  const column = index % columns

  const xStart = 14
  const xStep = 18
  const yStart = 20
  const yStep = 30

  return {
    x: xStart + (column * xStep),
    y: yStart + (row * yStep),
  }
}

function getTableLocationLabel(features) {
  if (!Array.isArray(features) || features.length === 0) {
    return 'No location set'
  }

  const knownLocations = LOCATION_OPTIONS
    .filter(option => option.value)
    .map(option => option.label)

  const exactMatch = features.find(feature => knownLocations.includes(feature))

  if (exactMatch) {
    return exactMatch
  }

  const firstFeature = features.find(feature => typeof feature === 'string' && feature.trim())
  return firstFeature || 'No location set'
}

function App() {
  const today = getDefaultDate()
  const [availableTimes, setAvailableTimes] = useState([])
  const [availableTables, setAvailableTables] = useState([])
  const [loading, setLoading] = useState(true)
  const [tableLoading, setTableLoading] = useState(false)
  const [error, setError] = useState('')
  const [tableError, setTableError] = useState('')
  const [date, setDate] = useState(getDefaultDate)
  const [guests, setGuests] = useState(2)
  const [location, setLocation] = useState('')
  const [selectedTime, setSelectedTime] = useState('')
  const [selectedTableId, setSelectedTableId] = useState('')
  const [showFloorPlan, setShowFloorPlan] = useState(false)
  const timeSections = getTimeSections(availableTimes)
  // Generated by AI - start
  const resetReservationView = () => {
    setSelectedTime('')
    setSelectedTableId('')
    setShowFloorPlan(false)
    setTableError('')
    setAvailableTables([])
  }

  const handleReserveClick = async () => {
    if (!selectedTime) {
      return
    }

    setTableLoading(true)
    setTableError('')

    try {
      const query = new URLSearchParams({
        date,
        time: selectedTime,
        guests: String(Math.max(1, guests)),
      })

      if (location) {
        query.set('location', location)
      }

      const res = await fetch(`/api/tables/availability?${query.toString()}`)

      if (!res.ok) {
        const status = `${res.status}${res.statusText ? ` ${res.statusText}` : ''}`
        const detail = (await res.text()).trim()
        throw new Error(`${status}${detail ? `: ${detail}` : ''}`)
      }

      const data = await res.json()
      const tables = Array.isArray(data?.tables) ? data.tables : []
      const orderedTables = [...tables].sort((a, b) => (a.tableNumber ?? 0) - (b.tableNumber ?? 0))
      setAvailableTables(orderedTables)
      setSelectedTableId('')
      setShowFloorPlan(true)
    } catch (err) {
      setTableError(err instanceof Error ? err.message : 'Failed to load table availability.')
      setSelectedTableId('')
      setShowFloorPlan(false)
      setAvailableTables([])
    } finally {
      setTableLoading(false)
    }
  }
  // Generated by AI - end
  useEffect(() => {
    const loadAvailableTimes = async () => {
      setLoading(true)
      setError('')

      try {
        const query = new URLSearchParams({
          date,
          guests: String(Math.max(1, guests)),
        })

        if (location) {
          query.set('location', location)
        }

        const res = await fetch(`/api/tables/available-times?${query.toString()}`)

        if (!res.ok) {
          const status = `${res.status}${res.statusText ? ` ${res.statusText}` : ''}`
          const contentType = res.headers.get('content-type') || ''
          let detail = ''

          if (contentType.includes('application/json')) {
            const body = await res.json()
            detail = body?.message || body?.error || ''
          } else {
            detail = await res.text()
          }

          const trimmedDetail = typeof detail === 'string' ? detail.trim() : ''
          throw new Error(
            `${status}${trimmedDetail ? `: ${trimmedDetail}` : ''}`
          )
        }

        const data = await res.json()
        const nextAvailableTimes = Array.isArray(data?.availableTimes) ? data.availableTimes : []
        setAvailableTimes(nextAvailableTimes)
        setSelectedTime((currentSelectedTime) => (
          nextAvailableTimes.includes(currentSelectedTime) ? currentSelectedTime : ''
        ))
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : 'Unknown error occurred.'
        )
        setAvailableTimes([])
        setSelectedTime('')
      } finally {
        setLoading(false)
      }
    }

    loadAvailableTimes()
  }, [date, guests, location])

  // Generated by AI - start
  return (
    <section className="availability-page">
      <header className="availability-header">
        <h1>CGI Restaurant</h1>
      </header>

      {!showFloorPlan && (
      <section className="filter-form" aria-label="Availability filters">
        <label>
          Date
          <input
            type="date"
            value={date}
            min={today}
            onChange={(event) => {
              const selectedDate = event.target.value
              setDate(selectedDate < today ? today : selectedDate)
              resetReservationView()
            }}
          />
        </label>

        <label>
          Number of people
          <input
            type="number"
            min="1"
            max="20"
            value={guests}
            onChange={(event) => {
              setGuests(Number(event.target.value) || 1)
              resetReservationView()
            }}
          />
        </label>

        <label>
          Location
          <select
            value={location}
            onChange={(event) => {
              setLocation(event.target.value)
              resetReservationView()
            }}
          >
            {LOCATION_OPTIONS.map(option => (
              <option key={option.label} value={option.value}>{option.label}</option>
            ))}
          </select>
        </label>

      </section>
      )}

      <section className="availability-results" aria-live="polite">
          {showFloorPlan ? (
            <div className="floor-plan-section">
              <div className="floor-plan-heading">
                <div>
                  <h2>{selectedTime ? `Reserve ${selectedTime}` : 'Floor Plan'}</h2>
                  <p>
                    {formatDateForDisplay(date)} at {selectedTime} for {Math.max(1, guests)} guests
                    {location ? ` in ${location}` : ''}
                  </p>
                </div>
                <button
                  type="button"
                  className="timeslot-cta floor-plan-back"
                  onClick={() => setShowFloorPlan(false)}
                >
                  Back
                </button>
              </div>

              {tableError ? (
                <p className="error-message" role="alert">
                  <span className="error-icon" aria-hidden="true">X</span>
                  <span>{tableError}</span>
                </p>
              ) : availableTables.length === 0 ? (
                <p>No tables were found for this reservation.</p>
              ) : (
                <>
                  <div className="floor-plan-legend" aria-label="Table availability legend">
                    <span className="legend-item"><span className="legend-dot available" aria-hidden="true" />Available</span>
                    <span className="legend-item"><span className="legend-dot unavailable" aria-hidden="true" />Unavailable</span>
                  </div>

                  <div className="floor-plan-canvas" role="img" aria-label="Restaurant floor plan with table availability">
                    {availableTables.map((table, index) => {
                      const position = getTablePosition(index)
                      const tableKey = String(table.id ?? table.tableNumber ?? index)

                      return (
                        <div
                          key={tableKey}
                          className={`floor-table ${table.recommended ? 'available' : 'unavailable'}${selectedTableId === tableKey ? ' selected' : ''}`}
                          style={{ left: `${position.x}%`, top: `${position.y}%` }}
                          onClick={() => {
                            if (!table.recommended) {
                              return
                            }

                            setSelectedTableId(tableKey)
                          }}
                        >
                          <strong>Table {table.tableNumber}</strong>
                          <span>{table.capacity} seats</span>
                          <span className="table-location">{getTableLocationLabel(table.features)}</span>
                        </div>
                      )
                    })}
                  </div>
                </>
              )}
            </div>
          ) : loading ? (
            <p>Loading available times...</p>
          ) : error ? (
            <p className="error-message" role="alert">
              <span className="error-icon" aria-hidden="true">X</span>
              <span>{error}</span>
            </p>
          ) : availableTimes.length === 0 ? (
            <p>No available start times for the selected criteria.</p>
          ) : (
            <div className="time-sections">
              {timeSections.map(section => (
                <section className="time-section" key={section.key}>
                  <h2>{section.title}</h2>
                  <ul className="time-list">
                    {section.times.map(time => (
                      <li key={`${section.key}-${time}`}>
                        <button
                          type="button"
                          className={`time-chip${selectedTime === time ? ' selected' : ''}`}
                          onClick={() => {
                            setSelectedTime(time)
                            setTableError('')
                          }}
                        >
                          {time}
                        </button>
                      </li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          )}

        {selectedTime && !loading && !error && availableTimes.length > 0 && (
          <div className="timeslot-cta-wrap">
            <button
              type="button"
              className="timeslot-cta"
              onClick={handleReserveClick}
              disabled={tableLoading}
            >
              {tableLoading ? 'Loading floor plan...' : 'Next'}
            </button>
          </div>
        )}

        {!showFloorPlan && tableError && (
          <p className="error-message" role="alert">
            <span className="error-icon" aria-hidden="true">X</span>
            <span>{tableError}</span>
          </p>
        )}

        <p className="reservation-info">
          <span className="reservation-info-icon" aria-hidden="true">i</span>
          <span>Morning and Lunch reservations are 1,5 hours. Evening reservations are 2,5 hours.</span>
        </p>
      </section>
    </section>
    // Generated by AI - end
  )
}

export default App
