package com.cgi.backend.config;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.cgi.backend.entity.Reservation;
import com.cgi.backend.entity.Table;
import com.cgi.backend.repository.ReservationRepository;
import com.cgi.backend.repository.TableRepository;


// This class was generated by AI
@Configuration
public class DataSeeder {

    private static final int OPENING_HOUR = 9;
    private static final int WEEKDAY_CLOSING_HOUR = 22;
    private static final int WEEKEND_CLOSING_HOUR = 23;
    private static final int SEEDING_WINDOW_DAYS = 21;
    private static final int WEEKDAY_RESERVATIONS_PER_DAY = 42;
    private static final int WEEKEND_RESERVATIONS_PER_DAY = 60;
    private static final int MORNING_LUNCH_DURATION_MINUTES = 90;
    private static final int EVENING_DURATION_MINUTES = 150;
    private static final int SLOT_STEP_MINUTES = 15;
    private static final double PEAK_HOUR_BIAS = 0.72;

    private static final List<TableSeedSpec> TABLE_SPECS = List.of(
        new TableSeedSpec(1, 4, "Near Window"),
        new TableSeedSpec(2, 4, "Regular"),
        new TableSeedSpec(3, 4, "Regular"),
        new TableSeedSpec(4, 2, "Private Booth"),
        new TableSeedSpec(5, 4, "Private Booth"),
        new TableSeedSpec(6, 4, "Near Window"),
        new TableSeedSpec(7, 2, "Regular"),
        new TableSeedSpec(8, 6, "Regular"),
        new TableSeedSpec(9, 2, "Regular"),
        new TableSeedSpec(10, 8, "Private Booth"),
        new TableSeedSpec(11, 2, "Near Window"),
        new TableSeedSpec(12, 4, "Regular"),
        new TableSeedSpec(13, 4, "Terrace"),
        new TableSeedSpec(14, 4, "Terrace"),
        new TableSeedSpec(15, 4, "Terrace")
    );

    @Bean
    CommandLineRunner seedData(TableRepository tableRepository, ReservationRepository reservationRepository) {
        return args -> {
            Random random = new Random();
            List<Table> existingTables = tableRepository.findAll();
            Map<Integer, Table> existingByTableNumber = existingTables.stream()
                .collect(Collectors.toMap(Table::getTableNumber, Function.identity(), (left, right) -> left));

            List<Table> upsertedTables = new ArrayList<>();
            for (TableSeedSpec spec : TABLE_SPECS) {
                Table existing = existingByTableNumber.get(spec.tableNumber());

                if (existing == null) {
                    upsertedTables.add(new Table(spec.tableNumber(), spec.capacity(), Set.of(spec.feature())));
                    continue;
                }

                existing.setCapacity(spec.capacity());
                existing.setFeatures(Set.of(spec.feature()));
                upsertedTables.add(existing);
            }

            if (!upsertedTables.isEmpty()) {
                tableRepository.saveAll(upsertedTables);
            }

            if (reservationRepository.count() > 0) {
                return;
            }

            List<Table> savedTables = tableRepository.findAll();
            List<Reservation> reservations = new ArrayList<>();
            LocalDate baseDate = LocalDate.now();

            for (int dayOffset = 0; dayOffset < SEEDING_WINDOW_DAYS; dayOffset++) {
                LocalDate reservationDate = baseDate.plusDays(dayOffset);
                boolean weekend = isWeekend(reservationDate);
                int dailyReservations = weekend ? WEEKEND_RESERVATIONS_PER_DAY : WEEKDAY_RESERVATIONS_PER_DAY;
                List<LocalDateTime> possibleStarts = buildPossibleStartTimes(reservationDate, weekend);

                if (possibleStarts.isEmpty()) {
                    continue;
                }

                for (int i = 0; i < dailyReservations; i++) {
                    Table table = savedTables.get(random.nextInt(savedTables.size()));
                    LocalDateTime startTime = pickPopularStartTime(random, possibleStarts);
                    int durationMinutes = reservationDurationMinutes(startTime);
                    LocalDateTime endTime = startTime.plusMinutes(durationMinutes);

                    int guestCount = 1 + random.nextInt(table.getCapacity());
                    reservations.add(new Reservation(table, reservationDate, startTime, endTime, guestCount));
                }
            }

            reservationRepository.saveAll(reservations);
        };
    }

    private static boolean isWeekend(LocalDate date) {
        DayOfWeek dayOfWeek = date.getDayOfWeek();
        return dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY;
    }

    private static List<LocalDateTime> buildPossibleStartTimes(LocalDate reservationDate, boolean weekend) {
        int closingHour = weekend ? WEEKEND_CLOSING_HOUR : WEEKDAY_CLOSING_HOUR;
        LocalDateTime openingTime = reservationDate.atTime(OPENING_HOUR, 0);
        LocalDateTime closingTime = reservationDate.atTime(closingHour, 0);

        List<LocalDateTime> starts = new ArrayList<>();
        for (LocalDateTime current = openingTime; current.isBefore(closingTime); current = current.plusMinutes(SLOT_STEP_MINUTES)) {
            int durationMinutes = reservationDurationMinutes(current);
            LocalDateTime endTime = current.plusMinutes(durationMinutes);
            if (!endTime.isAfter(closingTime)) {
                starts.add(current);
            }
        }

        return starts;
    }

    private static int reservationDurationMinutes(LocalDateTime startTime) {
        if (startTime.getHour() < 17) {
            return MORNING_LUNCH_DURATION_MINUTES;
        }

        return EVENING_DURATION_MINUTES;
    }

    private static LocalDateTime pickPopularStartTime(Random random, List<LocalDateTime> possibleStarts) {
        if (possibleStarts.isEmpty()) {
            throw new IllegalArgumentException("possibleStarts must not be empty");
        }

        if (random.nextDouble() > PEAK_HOUR_BIAS) {
            return possibleStarts.get(random.nextInt(possibleStarts.size()));
        }

        List<LocalDateTime> peakStarts = possibleStarts.stream()
            .filter(start -> {
                int hour = start.getHour();
                return (hour >= 12 && hour < 15) || (hour >= 18 && hour < 21);
            })
            .toList();

        if (peakStarts.isEmpty()) {
            return possibleStarts.get(random.nextInt(possibleStarts.size()));
        }

        return peakStarts.get(random.nextInt(peakStarts.size()));
    }

    private record TableSeedSpec(int tableNumber, int capacity, String feature) {
    }
}
