package com.cgi.backend.config;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.cgi.backend.entity.Reservation;
import com.cgi.backend.entity.Table;
import com.cgi.backend.repository.ReservationRepository;
import com.cgi.backend.repository.TableRepository;


// This class was generated by AI
@Configuration
public class DataSeeder {

    private static final List<String> FEATURE_POOL = List.of(
        "Near Window",
        "Private Booth",
        "Terrace",
        "Middle of the Room"
    );

    @Bean
    CommandLineRunner seedData(TableRepository tableRepository, ReservationRepository reservationRepository) {
        return args -> {
            if (tableRepository.count() > 0) {
                return;
            }

            Random random = new Random();
            List<Table> generatedTables = new ArrayList<>();

            for (int i = 1; i <= 10; i++) {
                int capacity = switch (random.nextInt(4)) {
                    case 0 -> 2;
                    case 1 -> 4;
                    case 2 -> 6;
                    default -> 8;
                };

                Set<String> features = randomFeatures(random);

                generatedTables.add(new Table(i, capacity, features));
            }

            List<Table> savedTables = tableRepository.saveAll(generatedTables);
            List<Reservation> reservations = new ArrayList<>();
            LocalDateTime baseTime = LocalDateTime.now().withMinute(0).withSecond(0).withNano(0);

            for (int i = 0; i < 6; i++) {
                Table table = savedTables.get(random.nextInt(savedTables.size()));

                int startOffsetHours = random.nextInt(10) - 2;
                LocalDateTime startTime = baseTime.plusHours(startOffsetHours);
                LocalDateTime endTime = startTime.plusHours(1 + random.nextInt(3));

                int guestCount = 1 + random.nextInt(table.getCapacity());
                reservations.add(new Reservation(table, startTime, endTime, guestCount));
            }

            reservationRepository.saveAll(reservations);
        };
    }

    private static Set<String> randomFeatures(Random random) {
        Set<String> selected = new HashSet<>();

        selected.add(FEATURE_POOL.get(random.nextInt(FEATURE_POOL.size())));

        return selected;
    }
}
